[package]
name = "oxidb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.4.0"
paste = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
bincode = "1.3" # For binary serialization of index
toml = "0.8.10"
byteorder = "1.4"
anyhow = "1.0"
serde_with = { version = "2.3.0", features = ["macros", "json", "base64"] }
uuid = { version = "1.8.0", features = ["v4"] }
hex = "0.4"

[dev-dependencies]
tempfile = "3.8" # Or a more recent compatible version
cargo-nextest = { version = "0.9" }

[workspace]
members = [
    "examples/data_type_tests",
    "examples/simple_blog",
    "examples/todo_app",
    "examples/user_auth_files",
]
resolver = "2"
