[package]
name = "oxidb"
version = "0.2.0"
edition = "2021"
authors = ["OxiDB Team"]
description = "A minimal, pure Rust libsql alternative with zero-cost abstractions"
license = "MIT"
repository = "https://github.com/oxidb/oxidb"
keywords = ["database", "sql", "rust", "libsql", "embedded"]
categories = ["database-implementations"]

[dependencies]
# Only essential dependencies - following YAGNI principle
# No serde, no thiserror, no external serialization - pure stdlib

[dev-dependencies]
# Minimal test dependencies
tempfile = "3.8"

[workspace]
members = [
    "examples/data_type_tests",
    "examples/simple_blog", 
    "examples/todo_app",
    "examples/user_auth_files",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
debug = true
opt-level = 0
